### ISSUE TITLE
Packaging Warnings

### ISSUE THREAD

**Issue by kabassmusic** [Cesio137/EngineUserSettings#2]
Hello. I'm getting these warnings when packaging for UE 5.2

![Screenshot 2023-07-08 194110](https://github.com/Cesio137/EngineUserSettings/assets/28176852/e2a56ec0-1aa8-445c-85f8-c96894562d25)

**Comment by Cesio137** [comment]
Ok I will try to fix it

**Comment by Cesio137** [comment]
guess it's fixed now

**Comment by kabassmusic** [comment]
> guess it's fixed now

Unfortunately the warnings are still showing up for me.

**Comment by Cesio137** [comment]
I release 5.0.3. I build to my self to see and it's fixed now
